name: alef

dependencies:
        - python=3.8
        - numpy==1.21.5
        - pandas==1.4.1
        - pymc3==3.11.4
        - scipy==1.10.1
        - testfixtures==8.3.0
        - Theano==1.0.4
        - matplotlib==3.7.2
        - pydantic==1.9.0
        - pytest==8.3.4
        - pytest-cov==5.0.0
        - seaborn==0.13.2
        - pip==24.3.1
        - dill==0.3.9
        - pip:
                - --extra-index-url https://download.pytorch.org/whl/cu116
                - tensorflow==2.8.0
                - gpflow==2.4.0
                - tensorflow-probability==0.16.0
                - scikit-learn==1.3.2
                - gpflux==0.3.0
                - torch==1.12.1+cu116
                - torchvision==0.13.1+cu116
                - torchaudio==0.12.1
                - gpytorch==1.11
                - gym==0.26.2
                - PyYAML==6.0.2
                - tensorboardX==2.6
                - easydict==1.13
                - amor-hyp-gp==0.1.1
                - black==24.8.0
                - pyro-ppl==1.7.0
                - openpyxl==3.0.10
                - plotly==5.13.0
                - kaleido==0.2.1
                - disjoint-set==0.7.4
