name: asal-tabpfn
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=25.3
  - python=3.13.9
  - pip:
      - attrdictionary==1.0.0
      - gpytorch==1.14.2
      - hydra-core==1.3.2
      - numpy==2.3.5
      - omegaconf==2.3.0
      - openpyxl==3.1.5
      - pandas==2.3.3
      - plotly==6.5.0
      - pydantic==2.12.4
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - tabpfn==6.0.6
      - torch==2.9.1
